spring:
  application:
    name: BaroLab
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:loyalty_card}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver