spring:
  application:
    name: BaroLab
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:BaroLab}
    username: ${DATABASE_USER:BaroLab}
    password: ${DATABASE_PASSWORD:BaroLab_password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86  400000 # 1 day

app:
  logging:
    slow-request-ms: 500
    slow-operation-ms: 500
    slow-external-ms: 200
